### PR TITLE
Use x/sys/unix for ioctl instead of rolling our own.

### PR DESCRIPTION
**Pull request by ericonr**
Keep FS_* constants which aren't listed in the package, and leave
SetAttr there, even though it's currently not used.

### CODE REVIEW

**Comment by ericonr** [comment]
Hm, I'm not 100% about `SetAttr`, actually. It might work just fine on little endian system, but technically speaking it's wrong. The man page is clear about the syscall taking a `int *` and not a `long *` (and C `int` is Go `int32`)

**Comment by Foxboron** [comment]
Ah, yes. Much better. Should probably learn to use the ioctl stuff myself instead of stealing wrappers from canonical :p I'll pull it and test it a bit :)

**Comment by ericonr** [comment]
https://github.com/golang/go/issues/45585 <-- caveat about using these functions; shouldn't be an issue for what platforms sbctl aims to support, but I think a comment is warranted, or I could use the (ugly) workaround I listed in the issue.

The only platform I can think of that'd be affected by this is big endian aarch64.

**Comment by ericonr** [comment]
I've added a comment.

**Pull request merged**
