### PR TITLE
feat(enroll-keys): add partial enrollment of keys

### PR DESCRIPTION
**Pull request by RiSKeD**
Allow keys to be partially enrolled via --partial flag.

### CODE REVIEW

**Comment by Foxboron** [comment]
Is it possible to get the use-cased described?

**Comment by RiSKeD** [comment]
We intend to use sbctl in some automated test cases for SecureBoot on a few platforms (key enrollment, resets, and rotation): 
To facilitate this, it would be nice to rollout/reset/rotate each key individually, so we can separate the tests for each hierarchy.
This will also include importing and using invalid keys besides valid ones in the future.

**Review by Foxboron — APPROVED** [review]

**Comment by Foxboron** [comment]
Sure, that makes sense. LGTM.

Thanks :)

**Comment by RiSKeD** [comment]
Could you merge the changes? I got another PR in the pipeline based on these changes :smile:

**Comment by Foxboron** [comment]
> Could you merge the changes? I got another PR in the pipeline based on these changes smile

Sorry, not all caught up after vacation so some ramp-up time expected :)

**Pull request merged**
