### PR TITLE
Add convenient aliases for some sub-commands

### PR DESCRIPTION
**Pull request by eNV25**
Add convenient aliases for some sub-commands.

Aliases added:

- `list-bundles`
  - `ls-bundles`
- `list-files`
  - `ls-files`
  - `ls`
- `remove-bundle`
  - `rm-bundle`
- `remove-file`
  - `rm-file`
  - `rm`

If you don't agree with the `ls` and `rm` aliases I can remove them.

### CODE REVIEW

**Comment by Foxboron** [comment]
Hmm, my first impression is that I like it. I need to think a bit and figure out if this could be confusing in the long run? But I don't see anything obvious at least.

**Comment by Foxboron** [comment]
These aliases should preferably be mentioned in the man page :)

https://github.com/Foxboron/sbctl/blob/master/docs/sbctl.8.txt

**Comment by ericonr** [comment]
I'm slightly against this, because wiki pages and tutorials other folks write about sbctl will end up using multiple different versions of each command, and I think that would be confusing if someone is trying to get a full picture of things.

Idk about you, but I run these rarely enough that length doesn't matter as much...

**Comment by eNV25** [comment]
I thought it would be a good idea because it's similar to `git ls-files` and `git rm`. I added the other aliases for completeness.

**Pull request merged**
